author: ThePark Staff
description: UHC for ThePark
main: net.thepark.uhc.UHC
name: UltraHardcore
version: '0.1'

commands:
   uhc:
      description: Main UHC command
      usage: /<command>
      aliases: []
   startgame:
      description: Starts the UHC game
      usage: /uhc startgame
      aliases: []